org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
jei_version=19.22.1.316
gtm_version=7.0.2
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.197
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=eup2p
mod_name=EUP2P
mod_license=MIT
mod_version=1.21.1-1.0.0
mod_group_id=com.jerry
mod_authors=Lost Myself
mod_description=P2P tunnel available for GTM's cable connection.
